from datetime import datetime


def generate_memory_entries(results: dict) -> list[str]:
    """Format extracted data as Claude memory edit entries."""
    entries = []
    for mem in results.get("memories", []):
        if mem and isinstance(mem, str):
            entries.append(mem.strip())
    for ctx in results.get("context", []):
        if ctx and isinstance(ctx, str):
            entries.append(ctx.strip())
    return list(dict.fromkeys(entries))  # preserve order, remove dupes


def generate_skill_docs(skills: list) -> dict[str, str]:
    """Generate Claude-compatible .md skill documents."""
    docs = {}
    for skill in skills:
        name = skill.get("name", "unknown")
        slug = name.lower().replace(" ", "-").replace("/", "-")[:50]
        description = skill.get("description", "")
        examples = skill.get("examples", [])
        examples_md = "\n".join(f"- {e}" for e in examples) if examples else "- N/A"

        doc = f"""---
name: {name}
description: {description}
source: migrated-from-chatgpt
generated: {datetime.now().isoformat()}
---

## Overview
{description}

## Known Use Cases
{examples_md}

## Usage Notes
This skill was automatically extracted from ChatGPT conversation history.
Review and refine before using in production Claude workflows.
"""
        docs[slug] = doc
    return docs


def generate_report(results: dict, conversation_count: int) -> str:
    """Generate a markdown migration summary report."""
    mem_count = len(results.get("memories", []))
    skill_count = len(results.get("skills", []))
    interest_count = len(results.get("interests", []))
    ctx_count = len(results.get("context", []))

    memories_md = (
        "\n".join(f"- {m}" for m in results.get("memories", []))
        or "_None extracted_"
    )
    skills_md = (
        "\n".join(
            f"- **{s['name']}**: {s.get('description', '')}"
            for s in results.get("skills", [])
        )
        or "_None extracted_"
    )
    interests_md = (
        "\n".join(f"- {i}" for i in results.get("interests", [])) or "_None extracted_"
    )
    context_md = (
        "\n".join(f"- {c}" for c in results.get("context", [])) or "_None extracted_"
    )

    return f"""# ChatGPT → Claude Migration Report

**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M UTC")}

---

## Summary

| Metric | Count |
|---|---|
| Conversations Processed | {conversation_count} |
| Memory Entries Extracted | {mem_count} |
| Skills Identified | {skill_count} |
| Interests Mapped | {interest_count} |
| Context Items | {ctx_count} |

---

## Memory Entries
_Import these via Claude's memory system (Settings → Memory)_

{memories_md}

---

## Skills Detected
_Place the generated `.md` files in your Claude skills directory_

{skills_md}

---

## Interests

{interests_md}

---

## Active Context / Ongoing Projects

{context_md}

---

## Next Steps

1. **Review** `memory_entries.json` — remove any incorrect or outdated items
2. **Import memories** — use the Claude memory UI or API to add each entry
3. **Install skills** — place `skills/*.md` files in your Claude skills directory
4. **Validate** — test a few prompts to confirm Claude has the right context
5. **Delete** this report once migration is confirmed

---
_Generated by the ChatGPT → Claude Migration Tool_
"""
